# Setup
title:               "TaT"
tagline:             "Thoughts and Tech"
description:         "Writes when bored coding. Codes when bored writing. A staunch believer of Creative AI (Arts and AI). Let get the machines' creations lionized!"
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
