# Setup
title:               "Vignesh R's Blog"
tagline:             ""
description:         "I am passionate about full stack deep learning, specifically in the computer vision domain. 
                      Full stack deep learning is building end to end components involved in a production DL system - training, 
                      tuning, testing, serving (REST), hosting and troubleshooting a DL based system/application."
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
