# Setup
title:                Vignesh's blog
tagline:             'Why should living things have all the fun? Let's lionize the machines!'
description:         'A staunch believer of Creative AI (Arts and AI)'
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
