# Setup
title:               Namaskara
tagline:             'Here are my deep learning works'
description:         'A Computer science engineering student interested in deep learning, android app development and node js.'
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
