# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Namaskara
tagline:             ''
description:         'A Computer science engineering student interested in deep learning, android app development and node js.'
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
