# Setup
title:               Vignesh's Blog
tagline:             'Life is nothing but an illusion. Make it interesting!'
description:         'A Computer science student,deep learning enthusiastic, developed android apps, knows node js and loves python.'
url:                 http://viggyr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vignesh R
  url:               https://twitter.com/coolrv9619
  email:             vigneshr9619@gmail.com

# Custom vars
version:             1.0.0
